# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  pull_request:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i --legacy-peer-deps
      - run: npm run build:lib
      - run: npm publish
      - run: wget https://npmmirror.com/sync/@kne/react-form-antd
    env:
      NODE_AUTH_TOKEN: ${{secrets.npm_token}}